version: '0.0.1'

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-data:/data
    command: server --console-address ":9001" /data
    networks:
      - ciphershare-net

  opensearch:
    image: opensearchproject/opensearch
    container_name: opensearch
    ports:
      - "9200:9200"
      - "9600:9600"
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=opensearchadmin
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    networks:
      - ciphershare-net

  dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      - OPENSEARCH_HOSTS='["http://opensearch:9200"]'
    networks:
      - ciphershare-net

volumes:
  minio-data:
  opensearch-data:
networks:
  ciphershare-net:
    driver: bridge
