spring:
  application:
    name: zulu
  datasource:
    url: jdbc:postgresql://localhost:5432/file_storage
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: not-decided@gmail.com
    password: project-password-not-decided-maybe
    properties:
        mail:
            smtp:
                auth: true
                starttls:
                    enable: true

minio:
    url: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket-name: file-storage
